sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        albums:
            routes:
                list: 'app.get_albums'
                detail: 'app.get_album'
    field_type_options:
        selection:
            album_selection:
                default_type: 'list_overlay'
                resource_key: 'albums'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'albums'
                        display_properties:
                            - 'title'
                        icon: 'su-storage'
                        label: 'app.album_selection_label'
                        overlay_title: 'app.select_albums'
            event_selection:
                default_type: 'list_overlay'
                resource_key: 'events'
                view:
                    name: 'app.event.add_form'
                    result_to_view:
                        id: 'id'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'events'
                        display_properties:
                            - 'name'
                        icon: 'su-calendar'
                        label: 'app.event_selection_label'
                        overlay_title: 'app.select_events'
        single_selection:
            single_album_selection:
                default_type: 'list_overlay'
                resource_key: 'albums'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'albums'
                        display_properties:
                            - 'title'
                        icon: 'su-storage'
                        empty_text: 'app.no_album_selected'
                        overlay_title: 'app.select_album'
            single_event_selection:
                default_type: 'list_overlay'
                resource_key: 'events'
                view:
                    name: 'app.event.add_form'
                    result_to_view:
                        id: 'id'
                types:
                    list_overlay:
                        adapter: 'table'
                        list_key: 'events'
                        display_properties:
                            - 'name'
                        icon: 'su-calendar'
                        empty_text: 'app.no_event_selected'
                        overlay_title: 'app.select_event'
